/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.View;

import br.com.Connection.ConnectionFactory;
import br.com.Controller.ControllerUsuario;
import br.com.Model.ModelUsuario;
import br.com.Singleton.GerenciadorDeTelas;
import br.com.Validacao.ValidacaoException;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author santos
 */
public class telaEditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroUsuario
     */
    public telaEditarUsuario() {
        initComponents();
        
    }
public void preencheUsuario(ModelUsuario usuario){
    lblId.setText(Integer.toString(usuario.getId()));
    tfNome.setText(usuario.getNome());
    tfLogin.setText(usuario.getLogin());
    tfFone.setText(usuario.getFoneuser());
    cbTipo.setSelectedIndex(Integer.parseInt(usuario.getTipo_usuario()));
    //System.out.println(tfNome.getText());
   // System.out.println(tfLogin.getText());
   // System.out.println(tfFone.getText());
   // System.out.println(cbTipo.getSelectedItem());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void editarUsuario() throws ValidacaoException {

        ModelUsuario u = new ModelUsuario();
        ControllerUsuario controller = new ControllerUsuario();

//        System.out.println(tfNome.getText());
//        System.out.println(tfFone.getText());
//        System.out.println(tfLogin.getText());
//        System.out.println(tfSenha.getText());
        testaCampos();

        String senha = tfSenha.getText();
        
        u.setId(Integer.parseInt(lblId.getText()));
        u.setNome(tfNome.getText());
        u.setFoneuser(tfFone.getText());
        u.setTipo_usuario(cbTipo.getSelectedItem().toString());
        u.setLogin(tfLogin.getText());
        u.setSenha(controller.criptSenha(senha));
        
        controller.update(u);

        lblId.setText("");
        cbTipo.setSelectedIndex(0);
        tfNome.setText("");
        tfFone.setText("");
        tfLogin.setText("");
        tfSenha.setText("");

        telaUsuario telauser = new telaUsuario();
        telauser.readJTable();
    }

    public boolean testaLogin(String login) {

        Connection con = ConnectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        boolean check = false;

        try {
            stmt = con.prepareStatement("SELECT * FROM usuario WHERE login = ?");
            stmt.setString(1, login);
            rs = stmt.executeQuery();
            if (rs.next()) {
//                String teste = rs.getString(1);
//                System.out.println("Login: " + teste);
                check = true;

            };

        } catch (SQLException ex) {
            Logger.getLogger(telaEditarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            ConnectionFactory.closeConnection(con, stmt, rs);
        }

        return check;
    }

    public void testaCampos() throws ValidacaoException {

        if (tfNome.getText().equals("") || tfNome.getText().length() > 20) {
            lblNome.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane, "Nome precisa ser Preenchido com até 20 caracteres", "Aviso do Sistema", JOptionPane.ERROR_MESSAGE);
            throw new ValidacaoException("Nome precisa ser Preenchido com até 20 caracteres");
        } else {
            lblNome.setForeground(Color.BLACK);
        };

        if (testaLogin(tfLogin.getText()) == true) {
            lblLogin.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane, "O Login informado já existe.", "Aviso do Sistema", JOptionPane.ERROR_MESSAGE);
            throw new ValidacaoException("O Login informado já existe.");

        } else {
            lblLogin.setForeground(Color.BLACK);
        };

        if (tfLogin.getText().length() < 4) {
            lblLogin.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane, "Login precisa ser Preenchido com no mínimo 4 caracteres", "Aviso do Sistema", JOptionPane.ERROR_MESSAGE);
            throw new ValidacaoException("Login precisa ser Preenchido com no mínimo 4 caracteres");

        } else {
            lblLogin.setForeground(Color.BLACK);
        };

        if (tfLogin.getText().length() > 10) {
            lblLogin.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane, "Login precisa ser Preenchido com até 10 caracteres", "Aviso do Sistema", JOptionPane.ERROR_MESSAGE);
            throw new ValidacaoException("Login precisa ser Preenchido com até 10 caracteres");

        } else {
            lblLogin.setForeground(Color.BLACK);
        };

        if (tfSenha.getText().length() < 8) {
            lblSenha.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane, "A senha deve conter no mínimo 8 caracteres!", "Aviso do Sistema", JOptionPane.ERROR_MESSAGE);
            throw new ValidacaoException("A senha deve conter no mínimo 8 caracteres!");

        } else {
            lblSenha.setForeground(Color.BLACK);
        }

        if (tfFone.getText().equals("")) {
            lblFone.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane, "Celular precisa ser Preenchido apenas com caracteres numericos", "Aviso do Sistema", JOptionPane.ERROR_MESSAGE);
            throw new ValidacaoException("Celular precisa ser Preenchido apenas com caracteres numericos");

        } else {
            lblFone.setForeground(Color.BLACK);
        };
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        tfSenha = new javax.swing.JTextField();
        lblFone = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblTipo1 = new javax.swing.JLabel();
        tfFone = new javax.swing.JFormattedTextField();
        lblId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Editar Usuário");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("EDITAR USUÁRIO");

        lblNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNome.setText("Nome");

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogin.setText("Login");

        lblSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSenha.setText("Senha");

        lblFone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFone.setText("Celular");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Administrador", " " }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(0, 102, 255));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("ATUALIZAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 102, 255));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblTipo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTipo1.setText("Tipo");

        try {
            tfFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome)
                            .addComponent(lblLogin)
                            .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSenha)
                            .addComponent(btnSalvar)
                            .addComponent(lblId))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFone)
                            .addComponent(cbTipo, 0, 150, Short.MAX_VALUE)
                            .addComponent(lblTipo1)
                            .addComponent(tfFone))))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblTipo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblFone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:

        this.dispose();
        telaUsuario telauser = new telaUsuario();

        GerenciadorDeTelas.getInstanse().getTelaUsuario().setVisible(true);
        telauser.readJTable();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Deseja Mesmo Alterar o Usuário ?");
        
        if(op == JOptionPane.YES_OPTION){
            
        
        try {
            editarUsuario();
        } catch (ValidacaoException ex) {
            Logger.getLogger(telaEditarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        telaUsuario telauser = new telaUsuario();

        GerenciadorDeTelas.getInstanse().getTelaUsuario().setVisible(true);
        telauser.readJTable();
    }//GEN-LAST:event_btnSalvarActionPerformed
    }
    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaEditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFone;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTipo1;
    private javax.swing.JFormattedTextField tfFone;
    private javax.swing.JTextField tfLogin;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSenha;
    // End of variables declaration//GEN-END:variables
}
