/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.View;


import br.com.Controller.ControllerUsuario;
import br.com.Model.ModelUsuario;
import br.com.Singleton.GerenciadorDeTelas;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author santos
 */
public class telaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form telaUsuario
     */
    public telaUsuario() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jtUsers.getModel();
        jtUsers.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }

    public void readJTable() {

        DefaultTableModel modelo = (DefaultTableModel) jtUsers.getModel();
        modelo.setNumRows(0);
        ControllerUsuario userContr = new ControllerUsuario();

        DefaultTableCellRenderer tabela = new DefaultTableCellRenderer();
        tabela.setHorizontalAlignment(SwingConstants.LEFT);
        jtUsers.getColumnModel().getColumn(0).setCellRenderer(tabela);

        for (ModelUsuario user : userContr.read()) {

            modelo.addRow(new Object[]{
                user.getId(),
                user.getNome(),
                user.getLogin(),
                user.getFoneuser(),
                user.getTipo_usuario(),});

        }

    }

    public void readJTableQuery(String usuario) {

        DefaultTableModel modelo = (DefaultTableModel) jtUsers.getModel();
        modelo.setNumRows(0);
        ControllerUsuario userContr = new ControllerUsuario();

        DefaultTableCellRenderer tabela = new DefaultTableCellRenderer();
        tabela.setHorizontalAlignment(SwingConstants.LEFT);
        jtUsers.getColumnModel().getColumn(0).setCellRenderer(tabela);

        for (ModelUsuario user : userContr.readQuery(usuario)) {

            modelo.addRow(new Object[]{
                user.getId(),
                user.getNome(),
                user.getLogin(),
                user.getFoneuser(),
                user.getTipo_usuario(),});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        tfLogin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblUsuarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtUsers = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuários");

        btnSair.setBackground(new java.awt.Color(0, 51, 255));
        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setText("SAIR");
        btnSair.setToolTipText("Fechar");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLogin.setText("Login");

        tfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoginActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/novo.png"))); // NOI18N
        jButton1.setText("NOVO");
        jButton1.setToolTipText("Cadastrar um novo usuário");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(102, 153, 255));
        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/excluir.png"))); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.setToolTipText("Selecione um usuário para excluir");
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/limpar10px.png"))); // NOI18N
        jButton3.setText("LIMPAR");
        jButton3.setToolTipText("Limpar filtro");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblUsuarios.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUsuarios.setText("USUÁRIOS");

        jtUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Login", "Fone", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtUsers.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtUsers.getTableHeader().setReorderingAllowed(false);
        jtUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsersMouseClicked(evt);
            }
        });
        jtUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtUsersKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtUsers);
        if (jtUsers.getColumnModel().getColumnCount() > 0) {
            jtUsers.getColumnModel().getColumn(0).setResizable(false);
            jtUsers.getColumnModel().getColumn(1).setResizable(false);
            jtUsers.getColumnModel().getColumn(2).setResizable(false);
            jtUsers.getColumnModel().getColumn(3).setResizable(false);
            jtUsers.getColumnModel().getColumn(4).setResizable(false);
        }

        btnEditar.setBackground(new java.awt.Color(102, 153, 255));
        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/editar.png"))); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.setToolTipText("Selecione um usuário para editar");
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 494, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(btnExcluir)
                                .addGap(69, 69, 69)
                                .addComponent(btnEditar))
                            .addComponent(jButton3)
                            .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogin)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(lblUsuarios)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarios)
                .addGap(33, 33, 33)
                .addComponent(lblLogin)
                .addGap(4, 4, 4)
                .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();

        GerenciadorDeTelas.getInstanse().getTelaCadastroUsuario().setVisible(true);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoginActionPerformed
        // TODO add your handling code here:
        telaCadastroUsuario controller = new telaCadastroUsuario();

        // System.out.println(controller.testaLogin(tfLogin.getText()));
        //  System.out.println(tfLogin.getText());
        if (controller.testaLogin(tfLogin.getText())) {

            readJTableQuery(tfLogin.getText());

        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuário não encontrado!", "Erro!", JOptionPane.ERROR_MESSAGE);
            tfLogin.setText("");
            readJTable();
        }

    }//GEN-LAST:event_tfLoginActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        tfLogin.setText("");
        readJTable();
   
        
    }//GEN-LAST:event_jButton3ActionPerformed

    ModelUsuario userModel = new ModelUsuario();
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (jtUsers.getSelectedRow() != -1) {
            this.dispose();
            GerenciadorDeTelas.getInstanse().getTelaEditarUsuario().setVisible(true);
            GerenciadorDeTelas.getInstanse().getTelaEditarUsuario().preencheUsuario(userModel);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Usuario", "Erro!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void jtUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsersMouseClicked

        userModel.setId(0);
        userModel.setNome("");
        userModel.setLogin("");
        userModel.setFoneuser("");
        userModel.setTipo_usuario("");
        if (jtUsers.getSelectedRow() != -1) {

            // DefaultTableModel modelo = (DefaultTableModel) jtUsers.getModel();
            userModel.setId(Integer.parseInt(jtUsers.getValueAt(jtUsers.getSelectedRow(), 0).toString()));
            //System.out.println(jtUsers.getValueAt(jtUsers.getSelectedRow(), 0).toString());
            userModel.setNome(jtUsers.getValueAt(jtUsers.getSelectedRow(), 1).toString());
            //System.out.println(jtUsers.getValueAt(jtUsers.getSelectedRow(), 0).toString());
            userModel.setLogin(jtUsers.getValueAt(jtUsers.getSelectedRow(), 2).toString());
            // System.out.println(jtUsers.getValueAt(jtUsers.getSelectedRow(), 1).toString());
            userModel.setFoneuser(jtUsers.getValueAt(jtUsers.getSelectedRow(), 3).toString());
            // System.out.println(jtUsers.getValueAt(jtUsers.getSelectedRow(), 2).toString());
            int tipo;
            if ("Usuario".equals(jtUsers.getValueAt(jtUsers.getSelectedRow(), 4).toString())) {
                tipo = 0;

            } else {
                tipo = 1;
            }
            userModel.setTipo_usuario(Integer.toString(tipo));
            //System.out.println(jtUsers.getValueAt(jtUsers.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_jtUsersMouseClicked

    private void jtUsersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUsersKeyReleased

        userModel.setId(0);
        userModel.setNome("");
        userModel.setLogin("");
        userModel.setFoneuser("");
        userModel.setTipo_usuario("");

        if (jtUsers.getSelectedRow() != -1) {

            DefaultTableModel modelo = (DefaultTableModel) jtUsers.getModel();
            userModel.setId(Integer.parseInt(jtUsers.getValueAt(jtUsers.getSelectedRow(), 0).toString()));
            //System.out.println(jtUsers.getValueAt(jtUsers.getSelectedRow(), 0).toString());
            userModel.setNome(jtUsers.getValueAt(jtUsers.getSelectedRow(), 1).toString());
            //System.out.println(jtUsers.getValueAt(jtUsers.getSelectedRow(), 0).toString());
            userModel.setLogin(jtUsers.getValueAt(jtUsers.getSelectedRow(), 2).toString());
            // System.out.println(jtUsers.getValueAt(jtUsers.getSelectedRow(), 1).toString());
            userModel.setFoneuser(jtUsers.getValueAt(jtUsers.getSelectedRow(), 3).toString());
            // System.out.println(jtUsers.getValueAt(jtUsers.getSelectedRow(), 2).toString());
            int tipo;
            if ("Usuario".equals(jtUsers.getValueAt(jtUsers.getSelectedRow(), 4).toString())) {
                tipo = 0;

            } else {
                tipo = 1;
            }
            userModel.setTipo_usuario(Integer.toString(tipo));
            //System.out.println(jtUsers.getValueAt(jtUsers.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_jtUsersKeyReleased

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (jtUsers.getSelectedRow() != -1) {
            System.out.println("ID: " + jtUsers.getValueAt(jtUsers.getSelectedRow(), 0) + "Nome: " + jtUsers.getValueAt(jtUsers.getSelectedRow(), 1));
            int op = JOptionPane.showConfirmDialog(this, "Deseja Mesmo Excluir o Usuário de ID = " + jtUsers.getValueAt(jtUsers.getSelectedRow(), 0)
                    + " " + "Nome: " + jtUsers.getValueAt(jtUsers.getSelectedRow(), 1), "Aviso do Sistema", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                ModelUsuario u = new ModelUsuario();
                ControllerUsuario controller = new ControllerUsuario();

                u.setId((int) jtUsers.getValueAt(jtUsers.getSelectedRow(), 0));

                controller.delete(u);

                // txtDesc.setText("");
                // txtQtd.setText("");
                // txtPreco.setText("");
                readJTable();

            }
            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtUsers;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblUsuarios;
    private javax.swing.JTextField tfLogin;
    // End of variables declaration//GEN-END:variables
}
